### ISSUE TITLE
Štruktúra dát v súbore pi_vtp.geojson

### ISSUE THREAD

**Issue by marcel-dancak** [CzechInvest/web-data#4]
Súbor 'pi_vtp.geojson' by mal byť obsahovať dáta viacerých vrstiev filtrovaných podľa atribútu 'type'. Ten má dátový typ String, a pri viacerých hodnotách používa ',' ako oddeľovač. V súboroch 'whoiswho.geojson' a 'dodavatele.geojson', z ktorých je taktiež potrebné filtrovať objekty pre rôzne vrstvy, je použitý dátovy typ pole. Otázka je, či by nebolo lepšie ujednotiť to a používať všade pole.

**Comment by jachym** [comment]
určitě, mrknu na to
