### ISSUE TITLE
Nekonzistentné dáta krajov

### ISSUE THREAD

**Issue by marcel-dancak** [CzechInvest/web-data#8]
Geometria krajov (geometry/kraje.geojson) a ich atribúty (socioekonomicka/soc_ekon-kraje.json) nie sú konzistentné. Obsahujú rôzny počet objektov a nesedia kódy, preto sa nedajú spojiť. Aj názvy krajov nie sú úplne totožné.

**Comment by jachym** [comment]
Mrknu

**Comment by jachym** [comment]
mělo by být opraveno @marcel-dancak  b9637e3
